// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dwango/nicolive/chat/data/atoms/akashic.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dwango.Nicolive.Chat.Data.Atoms {

  /// <summary>Holder for reflection information generated from dwango/nicolive/chat/data/atoms/akashic.proto</summary>
  public static partial class AkashicReflection {

    #region Descriptor
    /// <summary>File descriptor for dwango/nicolive/chat/data/atoms/akashic.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AkashicReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1kd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL2F0b21zL2FrYXNoaWMucHJv",
            "dG8SH2R3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXMaHGdvb2dsZS9w",
            "cm90b2J1Zi9zdHJ1Y3QucHJvdG8ihgEKE0FrYXNoaWNNZXNzYWdlRXZlbnQS",
            "DAoEdHlwZRgBIAEoCRIOCgZwbGF5SWQYAiABKAkSEQoJaWdub3JhYmxlGAMg",
            "ASgIEhEKCXRyYW5zaWVudBgEIAEoCBIrCgpwYXJhbWV0ZXJzGAUgASgLMhcu",
            "Z29vZ2xlLnByb3RvYnVmLlN0cnVjdCL6AQoTQWthc2hpY1N0YXRlUm91dGlu",
            "ZxINCgVlcG9jaBgBIAEoAxJCCgRqb2luGAIgAygLMjQuZHdhbmdvLm5pY29s",
            "aXZlLmNoYXQuZGF0YS5hdG9tcy5Ba2FzaGljTWVzc2FnZUV2ZW50EkoKDGNv",
            "bnRpbnVhdGlvbhgDIAMoCzI0LmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEu",
            "YXRvbXMuQWthc2hpY01lc3NhZ2VFdmVudBJECgZzaGFyZWQYBCADKAsyNC5k",
            "d2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zLkFrYXNoaWNNZXNzYWdl",
            "RXZlbnRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent), global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent.Parser, new[]{ "Type", "PlayId", "Ignorable", "Transient", "Parameters" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.AkashicStateRouting), global::Dwango.Nicolive.Chat.Data.Atoms.AkashicStateRouting.Parser, new[]{ "Epoch", "Join", "Continuation", "Shared" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AkashicMessageEvent : pb::IMessage<AkashicMessageEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AkashicMessageEvent> _parser = new pb::MessageParser<AkashicMessageEvent>(() => new AkashicMessageEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AkashicMessageEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dwango.Nicolive.Chat.Data.Atoms.AkashicReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AkashicMessageEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AkashicMessageEvent(AkashicMessageEvent other) : this() {
      type_ = other.type_;
      playId_ = other.playId_;
      ignorable_ = other.ignorable_;
      transient_ = other.transient_;
      parameters_ = other.parameters_ != null ? other.parameters_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AkashicMessageEvent Clone() {
      return new AkashicMessageEvent(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "playId" field.</summary>
    public const int PlayIdFieldNumber = 2;
    private string playId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PlayId {
      get { return playId_; }
      set {
        playId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ignorable" field.</summary>
    public const int IgnorableFieldNumber = 3;
    private bool ignorable_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Ignorable {
      get { return ignorable_; }
      set {
        ignorable_ = value;
      }
    }

    /// <summary>Field number for the "transient" field.</summary>
    public const int TransientFieldNumber = 4;
    private bool transient_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Transient {
      get { return transient_; }
      set {
        transient_ = value;
      }
    }

    /// <summary>Field number for the "parameters" field.</summary>
    public const int ParametersFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Struct parameters_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Struct Parameters {
      get { return parameters_; }
      set {
        parameters_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AkashicMessageEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AkashicMessageEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (PlayId != other.PlayId) return false;
      if (Ignorable != other.Ignorable) return false;
      if (Transient != other.Transient) return false;
      if (!object.Equals(Parameters, other.Parameters)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (PlayId.Length != 0) hash ^= PlayId.GetHashCode();
      if (Ignorable != false) hash ^= Ignorable.GetHashCode();
      if (Transient != false) hash ^= Transient.GetHashCode();
      if (parameters_ != null) hash ^= Parameters.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (PlayId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PlayId);
      }
      if (Ignorable != false) {
        output.WriteRawTag(24);
        output.WriteBool(Ignorable);
      }
      if (Transient != false) {
        output.WriteRawTag(32);
        output.WriteBool(Transient);
      }
      if (parameters_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Parameters);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (PlayId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PlayId);
      }
      if (Ignorable != false) {
        output.WriteRawTag(24);
        output.WriteBool(Ignorable);
      }
      if (Transient != false) {
        output.WriteRawTag(32);
        output.WriteBool(Transient);
      }
      if (parameters_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Parameters);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (PlayId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayId);
      }
      if (Ignorable != false) {
        size += 1 + 1;
      }
      if (Transient != false) {
        size += 1 + 1;
      }
      if (parameters_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Parameters);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AkashicMessageEvent other) {
      if (other == null) {
        return;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      if (other.PlayId.Length != 0) {
        PlayId = other.PlayId;
      }
      if (other.Ignorable != false) {
        Ignorable = other.Ignorable;
      }
      if (other.Transient != false) {
        Transient = other.Transient;
      }
      if (other.parameters_ != null) {
        if (parameters_ == null) {
          Parameters = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        Parameters.MergeFrom(other.Parameters);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 18: {
            PlayId = input.ReadString();
            break;
          }
          case 24: {
            Ignorable = input.ReadBool();
            break;
          }
          case 32: {
            Transient = input.ReadBool();
            break;
          }
          case 42: {
            if (parameters_ == null) {
              Parameters = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(Parameters);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 18: {
            PlayId = input.ReadString();
            break;
          }
          case 24: {
            Ignorable = input.ReadBool();
            break;
          }
          case 32: {
            Transient = input.ReadBool();
            break;
          }
          case 42: {
            if (parameters_ == null) {
              Parameters = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(Parameters);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AkashicStateRouting : pb::IMessage<AkashicStateRouting>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AkashicStateRouting> _parser = new pb::MessageParser<AkashicStateRouting>(() => new AkashicStateRouting());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AkashicStateRouting> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dwango.Nicolive.Chat.Data.Atoms.AkashicReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AkashicStateRouting() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AkashicStateRouting(AkashicStateRouting other) : this() {
      epoch_ = other.epoch_;
      join_ = other.join_.Clone();
      continuation_ = other.continuation_.Clone();
      shared_ = other.shared_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AkashicStateRouting Clone() {
      return new AkashicStateRouting(this);
    }

    /// <summary>Field number for the "epoch" field.</summary>
    public const int EpochFieldNumber = 1;
    private long epoch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Epoch {
      get { return epoch_; }
      set {
        epoch_ = value;
      }
    }

    /// <summary>Field number for the "join" field.</summary>
    public const int JoinFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent> _repeated_join_codec
        = pb::FieldCodec.ForMessage(18, global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent.Parser);
    private readonly pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent> join_ = new pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent> Join {
      get { return join_; }
    }

    /// <summary>Field number for the "continuation" field.</summary>
    public const int ContinuationFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent> _repeated_continuation_codec
        = pb::FieldCodec.ForMessage(26, global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent.Parser);
    private readonly pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent> continuation_ = new pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent> Continuation {
      get { return continuation_; }
    }

    /// <summary>Field number for the "shared" field.</summary>
    public const int SharedFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent> _repeated_shared_codec
        = pb::FieldCodec.ForMessage(34, global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent.Parser);
    private readonly pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent> shared_ = new pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.AkashicMessageEvent> Shared {
      get { return shared_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AkashicStateRouting);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AkashicStateRouting other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Epoch != other.Epoch) return false;
      if(!join_.Equals(other.join_)) return false;
      if(!continuation_.Equals(other.continuation_)) return false;
      if(!shared_.Equals(other.shared_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Epoch != 0L) hash ^= Epoch.GetHashCode();
      hash ^= join_.GetHashCode();
      hash ^= continuation_.GetHashCode();
      hash ^= shared_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Epoch != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Epoch);
      }
      join_.WriteTo(output, _repeated_join_codec);
      continuation_.WriteTo(output, _repeated_continuation_codec);
      shared_.WriteTo(output, _repeated_shared_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Epoch != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Epoch);
      }
      join_.WriteTo(ref output, _repeated_join_codec);
      continuation_.WriteTo(ref output, _repeated_continuation_codec);
      shared_.WriteTo(ref output, _repeated_shared_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Epoch != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Epoch);
      }
      size += join_.CalculateSize(_repeated_join_codec);
      size += continuation_.CalculateSize(_repeated_continuation_codec);
      size += shared_.CalculateSize(_repeated_shared_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AkashicStateRouting other) {
      if (other == null) {
        return;
      }
      if (other.Epoch != 0L) {
        Epoch = other.Epoch;
      }
      join_.Add(other.join_);
      continuation_.Add(other.continuation_);
      shared_.Add(other.shared_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Epoch = input.ReadInt64();
            break;
          }
          case 18: {
            join_.AddEntriesFrom(input, _repeated_join_codec);
            break;
          }
          case 26: {
            continuation_.AddEntriesFrom(input, _repeated_continuation_codec);
            break;
          }
          case 34: {
            shared_.AddEntriesFrom(input, _repeated_shared_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Epoch = input.ReadInt64();
            break;
          }
          case 18: {
            join_.AddEntriesFrom(ref input, _repeated_join_codec);
            break;
          }
          case 26: {
            continuation_.AddEntriesFrom(ref input, _repeated_continuation_codec);
            break;
          }
          case 34: {
            shared_.AddEntriesFrom(ref input, _repeated_shared_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
