// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dwango/nicolive/chat/data/atoms/creatorsupport.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dwango.Nicolive.Chat.Data.Atoms {

  /// <summary>Holder for reflection information generated from dwango/nicolive/chat/data/atoms/creatorsupport.proto</summary>
  public static partial class CreatorsupportReflection {

    #region Descriptor
    /// <summary>File descriptor for dwango/nicolive/chat/data/atoms/creatorsupport.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CreatorsupportReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL2F0b21zL2NyZWF0b3JzdXBw",
            "b3J0LnByb3RvEh9kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zIsAC",
            "ChhDcmVhdG9yU3VwcG9ydEdvYWxTdGF0dXMSDwoHZGlzcGxheRgBIAEoCBJd",
            "Cgpnb2FsU3RhdHVzGAIgASgLMkQuZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0",
            "YS5hdG9tcy5DcmVhdG9yU3VwcG9ydEdvYWxTdGF0dXMuR29hbFN0YXR1c0gA",
            "iAEBGqQBCgpHb2FsU3RhdHVzEhIKCnJld2FyZE5hbWUYAiABKAkSGQoRcmV3",
            "YXJkRGlzcGxheU5hbWUYAyABKAkSFQoNcHJvZ3Jlc3NSYXRpbxgEIAEoARIU",
            "CgxjdXJyZW50UG9pbnQYBSABKAMSEgoKbG93ZXJQb2ludBgGIAEoAxISCgp1",
            "cHBlclBvaW50GAcgASgDEhIKCmlzQWNoaWV2ZWQYCCABKAhCDQoLX2dvYWxT",
            "dGF0dXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.CreatorSupportGoalStatus), global::Dwango.Nicolive.Chat.Data.Atoms.CreatorSupportGoalStatus.Parser, new[]{ "Display", "GoalStatus" }, new[]{ "GoalStatus" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.CreatorSupportGoalStatus.Types.GoalStatus), global::Dwango.Nicolive.Chat.Data.Atoms.CreatorSupportGoalStatus.Types.GoalStatus.Parser, new[]{ "RewardName", "RewardDisplayName", "ProgressRatio", "CurrentPoint", "LowerPoint", "UpperPoint", "IsAchieved" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CreatorSupportGoalStatus : pb::IMessage<CreatorSupportGoalStatus>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreatorSupportGoalStatus> _parser = new pb::MessageParser<CreatorSupportGoalStatus>(() => new CreatorSupportGoalStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreatorSupportGoalStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dwango.Nicolive.Chat.Data.Atoms.CreatorsupportReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreatorSupportGoalStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreatorSupportGoalStatus(CreatorSupportGoalStatus other) : this() {
      display_ = other.display_;
      goalStatus_ = other.goalStatus_ != null ? other.goalStatus_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreatorSupportGoalStatus Clone() {
      return new CreatorSupportGoalStatus(this);
    }

    /// <summary>Field number for the "display" field.</summary>
    public const int DisplayFieldNumber = 1;
    private bool display_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Display {
      get { return display_; }
      set {
        display_ = value;
      }
    }

    /// <summary>Field number for the "goalStatus" field.</summary>
    public const int GoalStatusFieldNumber = 2;
    private global::Dwango.Nicolive.Chat.Data.Atoms.CreatorSupportGoalStatus.Types.GoalStatus goalStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.Atoms.CreatorSupportGoalStatus.Types.GoalStatus GoalStatus {
      get { return goalStatus_; }
      set {
        goalStatus_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreatorSupportGoalStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreatorSupportGoalStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Display != other.Display) return false;
      if (!object.Equals(GoalStatus, other.GoalStatus)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Display != false) hash ^= Display.GetHashCode();
      if (goalStatus_ != null) hash ^= GoalStatus.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Display != false) {
        output.WriteRawTag(8);
        output.WriteBool(Display);
      }
      if (goalStatus_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GoalStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Display != false) {
        output.WriteRawTag(8);
        output.WriteBool(Display);
      }
      if (goalStatus_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GoalStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Display != false) {
        size += 1 + 1;
      }
      if (goalStatus_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GoalStatus);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreatorSupportGoalStatus other) {
      if (other == null) {
        return;
      }
      if (other.Display != false) {
        Display = other.Display;
      }
      if (other.goalStatus_ != null) {
        if (goalStatus_ == null) {
          GoalStatus = new global::Dwango.Nicolive.Chat.Data.Atoms.CreatorSupportGoalStatus.Types.GoalStatus();
        }
        GoalStatus.MergeFrom(other.GoalStatus);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Display = input.ReadBool();
            break;
          }
          case 18: {
            if (goalStatus_ == null) {
              GoalStatus = new global::Dwango.Nicolive.Chat.Data.Atoms.CreatorSupportGoalStatus.Types.GoalStatus();
            }
            input.ReadMessage(GoalStatus);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Display = input.ReadBool();
            break;
          }
          case 18: {
            if (goalStatus_ == null) {
              GoalStatus = new global::Dwango.Nicolive.Chat.Data.Atoms.CreatorSupportGoalStatus.Types.GoalStatus();
            }
            input.ReadMessage(GoalStatus);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CreatorSupportGoalStatus message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class GoalStatus : pb::IMessage<GoalStatus>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<GoalStatus> _parser = new pb::MessageParser<GoalStatus>(() => new GoalStatus());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<GoalStatus> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Dwango.Nicolive.Chat.Data.Atoms.CreatorSupportGoalStatus.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GoalStatus() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GoalStatus(GoalStatus other) : this() {
          rewardName_ = other.rewardName_;
          rewardDisplayName_ = other.rewardDisplayName_;
          progressRatio_ = other.progressRatio_;
          currentPoint_ = other.currentPoint_;
          lowerPoint_ = other.lowerPoint_;
          upperPoint_ = other.upperPoint_;
          isAchieved_ = other.isAchieved_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GoalStatus Clone() {
          return new GoalStatus(this);
        }

        /// <summary>Field number for the "rewardName" field.</summary>
        public const int RewardNameFieldNumber = 2;
        private string rewardName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string RewardName {
          get { return rewardName_; }
          set {
            rewardName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "rewardDisplayName" field.</summary>
        public const int RewardDisplayNameFieldNumber = 3;
        private string rewardDisplayName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string RewardDisplayName {
          get { return rewardDisplayName_; }
          set {
            rewardDisplayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "progressRatio" field.</summary>
        public const int ProgressRatioFieldNumber = 4;
        private double progressRatio_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double ProgressRatio {
          get { return progressRatio_; }
          set {
            progressRatio_ = value;
          }
        }

        /// <summary>Field number for the "currentPoint" field.</summary>
        public const int CurrentPointFieldNumber = 5;
        private long currentPoint_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long CurrentPoint {
          get { return currentPoint_; }
          set {
            currentPoint_ = value;
          }
        }

        /// <summary>Field number for the "lowerPoint" field.</summary>
        public const int LowerPointFieldNumber = 6;
        private long lowerPoint_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long LowerPoint {
          get { return lowerPoint_; }
          set {
            lowerPoint_ = value;
          }
        }

        /// <summary>Field number for the "upperPoint" field.</summary>
        public const int UpperPointFieldNumber = 7;
        private long upperPoint_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long UpperPoint {
          get { return upperPoint_; }
          set {
            upperPoint_ = value;
          }
        }

        /// <summary>Field number for the "isAchieved" field.</summary>
        public const int IsAchievedFieldNumber = 8;
        private bool isAchieved_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool IsAchieved {
          get { return isAchieved_; }
          set {
            isAchieved_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as GoalStatus);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(GoalStatus other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (RewardName != other.RewardName) return false;
          if (RewardDisplayName != other.RewardDisplayName) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(ProgressRatio, other.ProgressRatio)) return false;
          if (CurrentPoint != other.CurrentPoint) return false;
          if (LowerPoint != other.LowerPoint) return false;
          if (UpperPoint != other.UpperPoint) return false;
          if (IsAchieved != other.IsAchieved) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (RewardName.Length != 0) hash ^= RewardName.GetHashCode();
          if (RewardDisplayName.Length != 0) hash ^= RewardDisplayName.GetHashCode();
          if (ProgressRatio != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(ProgressRatio);
          if (CurrentPoint != 0L) hash ^= CurrentPoint.GetHashCode();
          if (LowerPoint != 0L) hash ^= LowerPoint.GetHashCode();
          if (UpperPoint != 0L) hash ^= UpperPoint.GetHashCode();
          if (IsAchieved != false) hash ^= IsAchieved.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (RewardName.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(RewardName);
          }
          if (RewardDisplayName.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(RewardDisplayName);
          }
          if (ProgressRatio != 0D) {
            output.WriteRawTag(33);
            output.WriteDouble(ProgressRatio);
          }
          if (CurrentPoint != 0L) {
            output.WriteRawTag(40);
            output.WriteInt64(CurrentPoint);
          }
          if (LowerPoint != 0L) {
            output.WriteRawTag(48);
            output.WriteInt64(LowerPoint);
          }
          if (UpperPoint != 0L) {
            output.WriteRawTag(56);
            output.WriteInt64(UpperPoint);
          }
          if (IsAchieved != false) {
            output.WriteRawTag(64);
            output.WriteBool(IsAchieved);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (RewardName.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(RewardName);
          }
          if (RewardDisplayName.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(RewardDisplayName);
          }
          if (ProgressRatio != 0D) {
            output.WriteRawTag(33);
            output.WriteDouble(ProgressRatio);
          }
          if (CurrentPoint != 0L) {
            output.WriteRawTag(40);
            output.WriteInt64(CurrentPoint);
          }
          if (LowerPoint != 0L) {
            output.WriteRawTag(48);
            output.WriteInt64(LowerPoint);
          }
          if (UpperPoint != 0L) {
            output.WriteRawTag(56);
            output.WriteInt64(UpperPoint);
          }
          if (IsAchieved != false) {
            output.WriteRawTag(64);
            output.WriteBool(IsAchieved);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (RewardName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(RewardName);
          }
          if (RewardDisplayName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(RewardDisplayName);
          }
          if (ProgressRatio != 0D) {
            size += 1 + 8;
          }
          if (CurrentPoint != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(CurrentPoint);
          }
          if (LowerPoint != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(LowerPoint);
          }
          if (UpperPoint != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(UpperPoint);
          }
          if (IsAchieved != false) {
            size += 1 + 1;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(GoalStatus other) {
          if (other == null) {
            return;
          }
          if (other.RewardName.Length != 0) {
            RewardName = other.RewardName;
          }
          if (other.RewardDisplayName.Length != 0) {
            RewardDisplayName = other.RewardDisplayName;
          }
          if (other.ProgressRatio != 0D) {
            ProgressRatio = other.ProgressRatio;
          }
          if (other.CurrentPoint != 0L) {
            CurrentPoint = other.CurrentPoint;
          }
          if (other.LowerPoint != 0L) {
            LowerPoint = other.LowerPoint;
          }
          if (other.UpperPoint != 0L) {
            UpperPoint = other.UpperPoint;
          }
          if (other.IsAchieved != false) {
            IsAchieved = other.IsAchieved;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 18: {
                RewardName = input.ReadString();
                break;
              }
              case 26: {
                RewardDisplayName = input.ReadString();
                break;
              }
              case 33: {
                ProgressRatio = input.ReadDouble();
                break;
              }
              case 40: {
                CurrentPoint = input.ReadInt64();
                break;
              }
              case 48: {
                LowerPoint = input.ReadInt64();
                break;
              }
              case 56: {
                UpperPoint = input.ReadInt64();
                break;
              }
              case 64: {
                IsAchieved = input.ReadBool();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 18: {
                RewardName = input.ReadString();
                break;
              }
              case 26: {
                RewardDisplayName = input.ReadString();
                break;
              }
              case 33: {
                ProgressRatio = input.ReadDouble();
                break;
              }
              case 40: {
                CurrentPoint = input.ReadInt64();
                break;
              }
              case 48: {
                LowerPoint = input.ReadInt64();
                break;
              }
              case 56: {
                UpperPoint = input.ReadInt64();
                break;
              }
              case 64: {
                IsAchieved = input.ReadBool();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
