// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dwango/nicolive/chat/data/atoms/cruise.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dwango.Nicolive.Chat.Data.Atoms {

  /// <summary>Holder for reflection information generated from dwango/nicolive/chat/data/atoms/cruise.proto</summary>
  public static partial class CruiseReflection {

    #region Descriptor
    /// <summary>File descriptor for dwango/nicolive/chat/data/atoms/cruise.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CruiseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL2F0b21zL2NydWlzZS5wcm90",
            "bxIfZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5hdG9tcxofZ29vZ2xlL3By",
            "b3RvYnVmL3RpbWVzdGFtcC5wcm90byKZCAoUQ3J1aXNlUmVjZW50Q29udGVu",
            "dHMSTAoFaXRlbXMYASADKAsyPS5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRh",
            "LmF0b21zLkNydWlzZVJlY2VudENvbnRlbnRzLkNvbnRlbnQasgcKB0NvbnRl",
            "bnQSEQoJY29udGVudElkGAEgASgJEg0KBXRpdGxlGAIgASgJEhMKC2Rlc2Ny",
            "aXB0aW9uGAMgASgJElsKCnRodW1ibmFpbHMYBCABKAsyRy5kd2FuZ28ubmlj",
            "b2xpdmUuY2hhdC5kYXRhLmF0b21zLkNydWlzZVJlY2VudENvbnRlbnRzLkNv",
            "bnRlbnQuVGh1bWJuYWlsElcKCW9uQWlyVGltZRgFIAEoCzJELmR3YW5nby5u",
            "aWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXMuQ3J1aXNlUmVjZW50Q29udGVudHMu",
            "Q29udGVudC5QZXJpb2QSVgoIc2hvd1RpbWUYBiABKAsyRC5kd2FuZ28ubmlj",
            "b2xpdmUuY2hhdC5kYXRhLmF0b21zLkNydWlzZVJlY2VudENvbnRlbnRzLkNv",
            "bnRlbnQuUGVyaW9kEhQKB3ZpZXdlcnMYByABKAVIAYgBARIVCghjb21tZW50",
            "cxgIIAEoBUgCiAEBEmMKDWNoYW5uZWxfb3duZXIYCSABKAsySi5kd2FuZ28u",
            "bmljb2xpdmUuY2hhdC5kYXRhLmF0b21zLkNydWlzZVJlY2VudENvbnRlbnRz",
            "LkNvbnRlbnQuQ2hhbm5lbE93bmVySAASXQoKdXNlcl9vd25lchgKIAEoCzJH",
            "LmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXMuQ3J1aXNlUmVjZW50",
            "Q29udGVudHMuQ29udGVudC5Vc2VyT3duZXJIABppCglUaHVtYm5haWwSHgoW",
            "bGlzdGluZ1RodW1ibmFpbE1pZGRsZRgBIAEoCRIiChVsaXN0aW5nVGh1bWJu",
            "YWlsTGFyZ2UYAiABKAlIAIgBAUIYChZfbGlzdGluZ1RodW1ibmFpbExhcmdl",
            "Gm8KBlBlcmlvZBIrCgdiZWdpbkF0GAEgASgLMhouZ29vZ2xlLnByb3RvYnVm",
            "LlRpbWVzdGFtcBIuCgVlbmRBdBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5U",
            "aW1lc3RhbXBIAIgBAUIICgZfZW5kQXQaNgoMQ2hhbm5lbE93bmVyEgoKAmlk",
            "GAEgASgJEhEKBG5hbWUYAiABKAlIAIgBAUIHCgVfbmFtZRozCglVc2VyT3du",
            "ZXISCgoCaWQYASABKAkSEQoEbmFtZRgCIAEoCUgAiAEBQgcKBV9uYW1lQg8K",
            "DWNvbnRlbnRfb3duZXJCCgoIX3ZpZXdlcnNCCwoJX2NvbW1lbnRzYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents), global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Parser, new[]{ "Items" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content), global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Parser, new[]{ "ContentId", "Title", "Description", "Thumbnails", "OnAirTime", "ShowTime", "Viewers", "Comments", "ChannelOwner", "UserOwner" }, new[]{ "ContentOwner", "Viewers", "Comments" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Thumbnail), global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Thumbnail.Parser, new[]{ "ListingThumbnailMiddle", "ListingThumbnailLarge" }, new[]{ "ListingThumbnailLarge" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Period), global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Period.Parser, new[]{ "BeginAt", "EndAt" }, new[]{ "EndAt" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.ChannelOwner), global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.ChannelOwner.Parser, new[]{ "Id", "Name" }, new[]{ "Name" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.UserOwner), global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.UserOwner.Parser, new[]{ "Id", "Name" }, new[]{ "Name" }, null, null, null)})})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CruiseRecentContents : pb::IMessage<CruiseRecentContents>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CruiseRecentContents> _parser = new pb::MessageParser<CruiseRecentContents>(() => new CruiseRecentContents());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CruiseRecentContents> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dwango.Nicolive.Chat.Data.Atoms.CruiseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CruiseRecentContents() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CruiseRecentContents(CruiseRecentContents other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CruiseRecentContents Clone() {
      return new CruiseRecentContents(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Parser);
    private readonly pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content> items_ = new pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CruiseRecentContents);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CruiseRecentContents other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CruiseRecentContents other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CruiseRecentContents message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Content : pb::IMessage<Content>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Content> _parser = new pb::MessageParser<Content>(() => new Content());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Content> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Content() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Content(Content other) : this() {
          _hasBits0 = other._hasBits0;
          contentId_ = other.contentId_;
          title_ = other.title_;
          description_ = other.description_;
          thumbnails_ = other.thumbnails_ != null ? other.thumbnails_.Clone() : null;
          onAirTime_ = other.onAirTime_ != null ? other.onAirTime_.Clone() : null;
          showTime_ = other.showTime_ != null ? other.showTime_.Clone() : null;
          viewers_ = other.viewers_;
          comments_ = other.comments_;
          switch (other.ContentOwnerCase) {
            case ContentOwnerOneofCase.ChannelOwner:
              ChannelOwner = other.ChannelOwner.Clone();
              break;
            case ContentOwnerOneofCase.UserOwner:
              UserOwner = other.UserOwner.Clone();
              break;
          }

          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Content Clone() {
          return new Content(this);
        }

        /// <summary>Field number for the "contentId" field.</summary>
        public const int ContentIdFieldNumber = 1;
        private string contentId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ContentId {
          get { return contentId_; }
          set {
            contentId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "title" field.</summary>
        public const int TitleFieldNumber = 2;
        private string title_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Title {
          get { return title_; }
          set {
            title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "description" field.</summary>
        public const int DescriptionFieldNumber = 3;
        private string description_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Description {
          get { return description_; }
          set {
            description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "thumbnails" field.</summary>
        public const int ThumbnailsFieldNumber = 4;
        private global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Thumbnail thumbnails_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Thumbnail Thumbnails {
          get { return thumbnails_; }
          set {
            thumbnails_ = value;
          }
        }

        /// <summary>Field number for the "onAirTime" field.</summary>
        public const int OnAirTimeFieldNumber = 5;
        private global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Period onAirTime_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Period OnAirTime {
          get { return onAirTime_; }
          set {
            onAirTime_ = value;
          }
        }

        /// <summary>Field number for the "showTime" field.</summary>
        public const int ShowTimeFieldNumber = 6;
        private global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Period showTime_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Period ShowTime {
          get { return showTime_; }
          set {
            showTime_ = value;
          }
        }

        /// <summary>Field number for the "viewers" field.</summary>
        public const int ViewersFieldNumber = 7;
        private readonly static int ViewersDefaultValue = 0;

        private int viewers_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Viewers {
          get { if ((_hasBits0 & 1) != 0) { return viewers_; } else { return ViewersDefaultValue; } }
          set {
            _hasBits0 |= 1;
            viewers_ = value;
          }
        }
        /// <summary>Gets whether the "viewers" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasViewers {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "viewers" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearViewers() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "comments" field.</summary>
        public const int CommentsFieldNumber = 8;
        private readonly static int CommentsDefaultValue = 0;

        private int comments_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Comments {
          get { if ((_hasBits0 & 2) != 0) { return comments_; } else { return CommentsDefaultValue; } }
          set {
            _hasBits0 |= 2;
            comments_ = value;
          }
        }
        /// <summary>Gets whether the "comments" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasComments {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "comments" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearComments() {
          _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "channel_owner" field.</summary>
        public const int ChannelOwnerFieldNumber = 9;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.ChannelOwner ChannelOwner {
          get { return contentOwnerCase_ == ContentOwnerOneofCase.ChannelOwner ? (global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.ChannelOwner) contentOwner_ : null; }
          set {
            contentOwner_ = value;
            contentOwnerCase_ = value == null ? ContentOwnerOneofCase.None : ContentOwnerOneofCase.ChannelOwner;
          }
        }

        /// <summary>Field number for the "user_owner" field.</summary>
        public const int UserOwnerFieldNumber = 10;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.UserOwner UserOwner {
          get { return contentOwnerCase_ == ContentOwnerOneofCase.UserOwner ? (global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.UserOwner) contentOwner_ : null; }
          set {
            contentOwner_ = value;
            contentOwnerCase_ = value == null ? ContentOwnerOneofCase.None : ContentOwnerOneofCase.UserOwner;
          }
        }

        private object contentOwner_;
        /// <summary>Enum of possible cases for the "content_owner" oneof.</summary>
        public enum ContentOwnerOneofCase {
          None = 0,
          ChannelOwner = 9,
          UserOwner = 10,
        }
        private ContentOwnerOneofCase contentOwnerCase_ = ContentOwnerOneofCase.None;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ContentOwnerOneofCase ContentOwnerCase {
          get { return contentOwnerCase_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearContentOwner() {
          contentOwnerCase_ = ContentOwnerOneofCase.None;
          contentOwner_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Content);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Content other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ContentId != other.ContentId) return false;
          if (Title != other.Title) return false;
          if (Description != other.Description) return false;
          if (!object.Equals(Thumbnails, other.Thumbnails)) return false;
          if (!object.Equals(OnAirTime, other.OnAirTime)) return false;
          if (!object.Equals(ShowTime, other.ShowTime)) return false;
          if (Viewers != other.Viewers) return false;
          if (Comments != other.Comments) return false;
          if (!object.Equals(ChannelOwner, other.ChannelOwner)) return false;
          if (!object.Equals(UserOwner, other.UserOwner)) return false;
          if (ContentOwnerCase != other.ContentOwnerCase) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ContentId.Length != 0) hash ^= ContentId.GetHashCode();
          if (Title.Length != 0) hash ^= Title.GetHashCode();
          if (Description.Length != 0) hash ^= Description.GetHashCode();
          if (thumbnails_ != null) hash ^= Thumbnails.GetHashCode();
          if (onAirTime_ != null) hash ^= OnAirTime.GetHashCode();
          if (showTime_ != null) hash ^= ShowTime.GetHashCode();
          if (HasViewers) hash ^= Viewers.GetHashCode();
          if (HasComments) hash ^= Comments.GetHashCode();
          if (contentOwnerCase_ == ContentOwnerOneofCase.ChannelOwner) hash ^= ChannelOwner.GetHashCode();
          if (contentOwnerCase_ == ContentOwnerOneofCase.UserOwner) hash ^= UserOwner.GetHashCode();
          hash ^= (int) contentOwnerCase_;
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ContentId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(ContentId);
          }
          if (Title.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Title);
          }
          if (Description.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Description);
          }
          if (thumbnails_ != null) {
            output.WriteRawTag(34);
            output.WriteMessage(Thumbnails);
          }
          if (onAirTime_ != null) {
            output.WriteRawTag(42);
            output.WriteMessage(OnAirTime);
          }
          if (showTime_ != null) {
            output.WriteRawTag(50);
            output.WriteMessage(ShowTime);
          }
          if (HasViewers) {
            output.WriteRawTag(56);
            output.WriteInt32(Viewers);
          }
          if (HasComments) {
            output.WriteRawTag(64);
            output.WriteInt32(Comments);
          }
          if (contentOwnerCase_ == ContentOwnerOneofCase.ChannelOwner) {
            output.WriteRawTag(74);
            output.WriteMessage(ChannelOwner);
          }
          if (contentOwnerCase_ == ContentOwnerOneofCase.UserOwner) {
            output.WriteRawTag(82);
            output.WriteMessage(UserOwner);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ContentId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(ContentId);
          }
          if (Title.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Title);
          }
          if (Description.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Description);
          }
          if (thumbnails_ != null) {
            output.WriteRawTag(34);
            output.WriteMessage(Thumbnails);
          }
          if (onAirTime_ != null) {
            output.WriteRawTag(42);
            output.WriteMessage(OnAirTime);
          }
          if (showTime_ != null) {
            output.WriteRawTag(50);
            output.WriteMessage(ShowTime);
          }
          if (HasViewers) {
            output.WriteRawTag(56);
            output.WriteInt32(Viewers);
          }
          if (HasComments) {
            output.WriteRawTag(64);
            output.WriteInt32(Comments);
          }
          if (contentOwnerCase_ == ContentOwnerOneofCase.ChannelOwner) {
            output.WriteRawTag(74);
            output.WriteMessage(ChannelOwner);
          }
          if (contentOwnerCase_ == ContentOwnerOneofCase.UserOwner) {
            output.WriteRawTag(82);
            output.WriteMessage(UserOwner);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ContentId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ContentId);
          }
          if (Title.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
          }
          if (Description.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
          }
          if (thumbnails_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Thumbnails);
          }
          if (onAirTime_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(OnAirTime);
          }
          if (showTime_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShowTime);
          }
          if (HasViewers) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Viewers);
          }
          if (HasComments) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Comments);
          }
          if (contentOwnerCase_ == ContentOwnerOneofCase.ChannelOwner) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChannelOwner);
          }
          if (contentOwnerCase_ == ContentOwnerOneofCase.UserOwner) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserOwner);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Content other) {
          if (other == null) {
            return;
          }
          if (other.ContentId.Length != 0) {
            ContentId = other.ContentId;
          }
          if (other.Title.Length != 0) {
            Title = other.Title;
          }
          if (other.Description.Length != 0) {
            Description = other.Description;
          }
          if (other.thumbnails_ != null) {
            if (thumbnails_ == null) {
              Thumbnails = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Thumbnail();
            }
            Thumbnails.MergeFrom(other.Thumbnails);
          }
          if (other.onAirTime_ != null) {
            if (onAirTime_ == null) {
              OnAirTime = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Period();
            }
            OnAirTime.MergeFrom(other.OnAirTime);
          }
          if (other.showTime_ != null) {
            if (showTime_ == null) {
              ShowTime = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Period();
            }
            ShowTime.MergeFrom(other.ShowTime);
          }
          if (other.HasViewers) {
            Viewers = other.Viewers;
          }
          if (other.HasComments) {
            Comments = other.Comments;
          }
          switch (other.ContentOwnerCase) {
            case ContentOwnerOneofCase.ChannelOwner:
              if (ChannelOwner == null) {
                ChannelOwner = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.ChannelOwner();
              }
              ChannelOwner.MergeFrom(other.ChannelOwner);
              break;
            case ContentOwnerOneofCase.UserOwner:
              if (UserOwner == null) {
                UserOwner = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.UserOwner();
              }
              UserOwner.MergeFrom(other.UserOwner);
              break;
          }

          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                ContentId = input.ReadString();
                break;
              }
              case 18: {
                Title = input.ReadString();
                break;
              }
              case 26: {
                Description = input.ReadString();
                break;
              }
              case 34: {
                if (thumbnails_ == null) {
                  Thumbnails = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Thumbnail();
                }
                input.ReadMessage(Thumbnails);
                break;
              }
              case 42: {
                if (onAirTime_ == null) {
                  OnAirTime = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Period();
                }
                input.ReadMessage(OnAirTime);
                break;
              }
              case 50: {
                if (showTime_ == null) {
                  ShowTime = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Period();
                }
                input.ReadMessage(ShowTime);
                break;
              }
              case 56: {
                Viewers = input.ReadInt32();
                break;
              }
              case 64: {
                Comments = input.ReadInt32();
                break;
              }
              case 74: {
                global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.ChannelOwner subBuilder = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.ChannelOwner();
                if (contentOwnerCase_ == ContentOwnerOneofCase.ChannelOwner) {
                  subBuilder.MergeFrom(ChannelOwner);
                }
                input.ReadMessage(subBuilder);
                ChannelOwner = subBuilder;
                break;
              }
              case 82: {
                global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.UserOwner subBuilder = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.UserOwner();
                if (contentOwnerCase_ == ContentOwnerOneofCase.UserOwner) {
                  subBuilder.MergeFrom(UserOwner);
                }
                input.ReadMessage(subBuilder);
                UserOwner = subBuilder;
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                ContentId = input.ReadString();
                break;
              }
              case 18: {
                Title = input.ReadString();
                break;
              }
              case 26: {
                Description = input.ReadString();
                break;
              }
              case 34: {
                if (thumbnails_ == null) {
                  Thumbnails = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Thumbnail();
                }
                input.ReadMessage(Thumbnails);
                break;
              }
              case 42: {
                if (onAirTime_ == null) {
                  OnAirTime = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Period();
                }
                input.ReadMessage(OnAirTime);
                break;
              }
              case 50: {
                if (showTime_ == null) {
                  ShowTime = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.Period();
                }
                input.ReadMessage(ShowTime);
                break;
              }
              case 56: {
                Viewers = input.ReadInt32();
                break;
              }
              case 64: {
                Comments = input.ReadInt32();
                break;
              }
              case 74: {
                global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.ChannelOwner subBuilder = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.ChannelOwner();
                if (contentOwnerCase_ == ContentOwnerOneofCase.ChannelOwner) {
                  subBuilder.MergeFrom(ChannelOwner);
                }
                input.ReadMessage(subBuilder);
                ChannelOwner = subBuilder;
                break;
              }
              case 82: {
                global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.UserOwner subBuilder = new global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Types.UserOwner();
                if (contentOwnerCase_ == ContentOwnerOneofCase.UserOwner) {
                  subBuilder.MergeFrom(UserOwner);
                }
                input.ReadMessage(subBuilder);
                UserOwner = subBuilder;
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the Content message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class Thumbnail : pb::IMessage<Thumbnail>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<Thumbnail> _parser = new pb::MessageParser<Thumbnail>(() => new Thumbnail());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<Thumbnail> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Thumbnail() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Thumbnail(Thumbnail other) : this() {
              listingThumbnailMiddle_ = other.listingThumbnailMiddle_;
              listingThumbnailLarge_ = other.listingThumbnailLarge_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Thumbnail Clone() {
              return new Thumbnail(this);
            }

            /// <summary>Field number for the "listingThumbnailMiddle" field.</summary>
            public const int ListingThumbnailMiddleFieldNumber = 1;
            private string listingThumbnailMiddle_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string ListingThumbnailMiddle {
              get { return listingThumbnailMiddle_; }
              set {
                listingThumbnailMiddle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "listingThumbnailLarge" field.</summary>
            public const int ListingThumbnailLargeFieldNumber = 2;
            private readonly static string ListingThumbnailLargeDefaultValue = "";

            private string listingThumbnailLarge_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string ListingThumbnailLarge {
              get { return listingThumbnailLarge_ ?? ListingThumbnailLargeDefaultValue; }
              set {
                listingThumbnailLarge_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }
            /// <summary>Gets whether the "listingThumbnailLarge" field is set</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool HasListingThumbnailLarge {
              get { return listingThumbnailLarge_ != null; }
            }
            /// <summary>Clears the value of the "listingThumbnailLarge" field</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void ClearListingThumbnailLarge() {
              listingThumbnailLarge_ = null;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as Thumbnail);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(Thumbnail other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (ListingThumbnailMiddle != other.ListingThumbnailMiddle) return false;
              if (ListingThumbnailLarge != other.ListingThumbnailLarge) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (ListingThumbnailMiddle.Length != 0) hash ^= ListingThumbnailMiddle.GetHashCode();
              if (HasListingThumbnailLarge) hash ^= ListingThumbnailLarge.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (ListingThumbnailMiddle.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(ListingThumbnailMiddle);
              }
              if (HasListingThumbnailLarge) {
                output.WriteRawTag(18);
                output.WriteString(ListingThumbnailLarge);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (ListingThumbnailMiddle.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(ListingThumbnailMiddle);
              }
              if (HasListingThumbnailLarge) {
                output.WriteRawTag(18);
                output.WriteString(ListingThumbnailLarge);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (ListingThumbnailMiddle.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(ListingThumbnailMiddle);
              }
              if (HasListingThumbnailLarge) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(ListingThumbnailLarge);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(Thumbnail other) {
              if (other == null) {
                return;
              }
              if (other.ListingThumbnailMiddle.Length != 0) {
                ListingThumbnailMiddle = other.ListingThumbnailMiddle;
              }
              if (other.HasListingThumbnailLarge) {
                ListingThumbnailLarge = other.ListingThumbnailLarge;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    ListingThumbnailMiddle = input.ReadString();
                    break;
                  }
                  case 18: {
                    ListingThumbnailLarge = input.ReadString();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 10: {
                    ListingThumbnailMiddle = input.ReadString();
                    break;
                  }
                  case 18: {
                    ListingThumbnailLarge = input.ReadString();
                    break;
                  }
                }
              }
            }
            #endif

          }

          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class Period : pb::IMessage<Period>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<Period> _parser = new pb::MessageParser<Period>(() => new Period());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<Period> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Descriptor.NestedTypes[1]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Period() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Period(Period other) : this() {
              beginAt_ = other.beginAt_ != null ? other.beginAt_.Clone() : null;
              endAt_ = other.endAt_ != null ? other.endAt_.Clone() : null;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Period Clone() {
              return new Period(this);
            }

            /// <summary>Field number for the "beginAt" field.</summary>
            public const int BeginAtFieldNumber = 1;
            private global::Google.Protobuf.WellKnownTypes.Timestamp beginAt_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::Google.Protobuf.WellKnownTypes.Timestamp BeginAt {
              get { return beginAt_; }
              set {
                beginAt_ = value;
              }
            }

            /// <summary>Field number for the "endAt" field.</summary>
            public const int EndAtFieldNumber = 2;
            private global::Google.Protobuf.WellKnownTypes.Timestamp endAt_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::Google.Protobuf.WellKnownTypes.Timestamp EndAt {
              get { return endAt_; }
              set {
                endAt_ = value;
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as Period);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(Period other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (!object.Equals(BeginAt, other.BeginAt)) return false;
              if (!object.Equals(EndAt, other.EndAt)) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (beginAt_ != null) hash ^= BeginAt.GetHashCode();
              if (endAt_ != null) hash ^= EndAt.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (beginAt_ != null) {
                output.WriteRawTag(10);
                output.WriteMessage(BeginAt);
              }
              if (endAt_ != null) {
                output.WriteRawTag(18);
                output.WriteMessage(EndAt);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (beginAt_ != null) {
                output.WriteRawTag(10);
                output.WriteMessage(BeginAt);
              }
              if (endAt_ != null) {
                output.WriteRawTag(18);
                output.WriteMessage(EndAt);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (beginAt_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(BeginAt);
              }
              if (endAt_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(EndAt);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(Period other) {
              if (other == null) {
                return;
              }
              if (other.beginAt_ != null) {
                if (beginAt_ == null) {
                  BeginAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                BeginAt.MergeFrom(other.BeginAt);
              }
              if (other.endAt_ != null) {
                if (endAt_ == null) {
                  EndAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                EndAt.MergeFrom(other.EndAt);
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    if (beginAt_ == null) {
                      BeginAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                    }
                    input.ReadMessage(BeginAt);
                    break;
                  }
                  case 18: {
                    if (endAt_ == null) {
                      EndAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                    }
                    input.ReadMessage(EndAt);
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 10: {
                    if (beginAt_ == null) {
                      BeginAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                    }
                    input.ReadMessage(BeginAt);
                    break;
                  }
                  case 18: {
                    if (endAt_ == null) {
                      EndAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                    }
                    input.ReadMessage(EndAt);
                    break;
                  }
                }
              }
            }
            #endif

          }

          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class ChannelOwner : pb::IMessage<ChannelOwner>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<ChannelOwner> _parser = new pb::MessageParser<ChannelOwner>(() => new ChannelOwner());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<ChannelOwner> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Descriptor.NestedTypes[2]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ChannelOwner() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ChannelOwner(ChannelOwner other) : this() {
              id_ = other.id_;
              name_ = other.name_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ChannelOwner Clone() {
              return new ChannelOwner(this);
            }

            /// <summary>Field number for the "id" field.</summary>
            public const int IdFieldNumber = 1;
            private string id_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string Id {
              get { return id_; }
              set {
                id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "name" field.</summary>
            public const int NameFieldNumber = 2;
            private readonly static string NameDefaultValue = "";

            private string name_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string Name {
              get { return name_ ?? NameDefaultValue; }
              set {
                name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }
            /// <summary>Gets whether the "name" field is set</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool HasName {
              get { return name_ != null; }
            }
            /// <summary>Clears the value of the "name" field</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void ClearName() {
              name_ = null;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as ChannelOwner);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(ChannelOwner other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Id != other.Id) return false;
              if (Name != other.Name) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (Id.Length != 0) hash ^= Id.GetHashCode();
              if (HasName) hash ^= Name.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (Id.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(Id);
              }
              if (HasName) {
                output.WriteRawTag(18);
                output.WriteString(Name);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (Id.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(Id);
              }
              if (HasName) {
                output.WriteRawTag(18);
                output.WriteString(Name);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (Id.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
              }
              if (HasName) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(ChannelOwner other) {
              if (other == null) {
                return;
              }
              if (other.Id.Length != 0) {
                Id = other.Id;
              }
              if (other.HasName) {
                Name = other.Name;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    Id = input.ReadString();
                    break;
                  }
                  case 18: {
                    Name = input.ReadString();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 10: {
                    Id = input.ReadString();
                    break;
                  }
                  case 18: {
                    Name = input.ReadString();
                    break;
                  }
                }
              }
            }
            #endif

          }

          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class UserOwner : pb::IMessage<UserOwner>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<UserOwner> _parser = new pb::MessageParser<UserOwner>(() => new UserOwner());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<UserOwner> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Dwango.Nicolive.Chat.Data.Atoms.CruiseRecentContents.Types.Content.Descriptor.NestedTypes[3]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public UserOwner() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public UserOwner(UserOwner other) : this() {
              id_ = other.id_;
              name_ = other.name_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public UserOwner Clone() {
              return new UserOwner(this);
            }

            /// <summary>Field number for the "id" field.</summary>
            public const int IdFieldNumber = 1;
            private string id_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string Id {
              get { return id_; }
              set {
                id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "name" field.</summary>
            public const int NameFieldNumber = 2;
            private readonly static string NameDefaultValue = "";

            private string name_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string Name {
              get { return name_ ?? NameDefaultValue; }
              set {
                name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }
            /// <summary>Gets whether the "name" field is set</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool HasName {
              get { return name_ != null; }
            }
            /// <summary>Clears the value of the "name" field</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void ClearName() {
              name_ = null;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as UserOwner);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(UserOwner other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Id != other.Id) return false;
              if (Name != other.Name) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (Id.Length != 0) hash ^= Id.GetHashCode();
              if (HasName) hash ^= Name.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (Id.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(Id);
              }
              if (HasName) {
                output.WriteRawTag(18);
                output.WriteString(Name);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (Id.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(Id);
              }
              if (HasName) {
                output.WriteRawTag(18);
                output.WriteString(Name);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (Id.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
              }
              if (HasName) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(UserOwner other) {
              if (other == null) {
                return;
              }
              if (other.Id.Length != 0) {
                Id = other.Id;
              }
              if (other.HasName) {
                Name = other.Name;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    Id = input.ReadString();
                    break;
                  }
                  case 18: {
                    Name = input.ReadString();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 10: {
                    Id = input.ReadString();
                    break;
                  }
                  case 18: {
                    Name = input.ReadString();
                    break;
                  }
                }
              }
            }
            #endif

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
