// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dwango/nicolive/chat/data/atoms/ichibalauncher.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dwango.Nicolive.Chat.Data.Atoms {

  /// <summary>Holder for reflection information generated from dwango/nicolive/chat/data/atoms/ichibalauncher.proto</summary>
  public static partial class IchibalauncherReflection {

    #region Descriptor
    /// <summary>File descriptor for dwango/nicolive/chat/data/atoms/ichibalauncher.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IchibalauncherReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL2F0b21zL2ljaGliYWxhdW5j",
            "aGVyLnByb3RvEh9kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zIo4E",
            "ChVJY2hpYmFMYXVuY2hlckl0ZW1TZXQSDQoFZXBvY2gYASABKAMSSgoFaXRl",
            "bXMYAiADKAsyOy5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zLklj",
            "aGliYUxhdW5jaGVySXRlbVNldC5JdGVtGpkDCgRJdGVtEgoKAmlkGAEgASgJ",
            "EhAKCGVudGl0eUlkGAIgASgJEhMKC3NlcnZpY2VOYW1lGAMgASgJEg0KBXRp",
            "dGxlGAQgASgJEmYKEGxhdW5jaERpYWxvZ1R5cGUYBSABKA4yTC5kd2FuZ28u",
            "bmljb2xpdmUuY2hhdC5kYXRhLmF0b21zLkljaGliYUxhdW5jaGVySXRlbVNl",
            "dC5JdGVtLkxhdW5jaERpYWxvZ1R5cGUSFAoMdGh1bWJuYWlsVXJsGAYgASgJ",
            "EhYKDnRodW1ibmFpbFdpZHRoGAcgASgFEhcKD3RodW1ibmFpbEhlaWdodBgI",
            "IAEoBRIRCglsYXVuY2hVcmwYCSABKAkSGAoLYWRkZWRVc2VySWQYCiABKAlI",
            "AIgBARIWCglyZXBvcnRVcmwYCyABKAlIAYgBARIPCgdydW5uaW5nGAwgASgI",
            "IiwKEExhdW5jaERpYWxvZ1R5cGUSCQoFU01BTEwQABINCglSSUNISVZJRVcQ",
            "AUIOCgxfYWRkZWRVc2VySWRCDAoKX3JlcG9ydFVybGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet), global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Parser, new[]{ "Epoch", "Items" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item), global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Parser, new[]{ "Id", "EntityId", "ServiceName", "Title", "LaunchDialogType", "ThumbnailUrl", "ThumbnailWidth", "ThumbnailHeight", "LaunchUrl", "AddedUserId", "ReportUrl", "Running" }, new[]{ "AddedUserId", "ReportUrl" }, new[]{ typeof(global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Types.LaunchDialogType) }, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class IchibaLauncherItemSet : pb::IMessage<IchibaLauncherItemSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IchibaLauncherItemSet> _parser = new pb::MessageParser<IchibaLauncherItemSet>(() => new IchibaLauncherItemSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IchibaLauncherItemSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dwango.Nicolive.Chat.Data.Atoms.IchibalauncherReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IchibaLauncherItemSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IchibaLauncherItemSet(IchibaLauncherItemSet other) : this() {
      epoch_ = other.epoch_;
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IchibaLauncherItemSet Clone() {
      return new IchibaLauncherItemSet(this);
    }

    /// <summary>Field number for the "epoch" field.</summary>
    public const int EpochFieldNumber = 1;
    private long epoch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Epoch {
      get { return epoch_; }
      set {
        epoch_ = value;
      }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item> _repeated_items_codec
        = pb::FieldCodec.ForMessage(18, global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Parser);
    private readonly pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item> items_ = new pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IchibaLauncherItemSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IchibaLauncherItemSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Epoch != other.Epoch) return false;
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Epoch != 0L) hash ^= Epoch.GetHashCode();
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Epoch != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Epoch);
      }
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Epoch != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Epoch);
      }
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Epoch != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Epoch);
      }
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IchibaLauncherItemSet other) {
      if (other == null) {
        return;
      }
      if (other.Epoch != 0L) {
        Epoch = other.Epoch;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Epoch = input.ReadInt64();
            break;
          }
          case 18: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Epoch = input.ReadInt64();
            break;
          }
          case 18: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the IchibaLauncherItemSet message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Item : pb::IMessage<Item>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Item> _parser = new pb::MessageParser<Item>(() => new Item());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Item> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Item() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Item(Item other) : this() {
          id_ = other.id_;
          entityId_ = other.entityId_;
          serviceName_ = other.serviceName_;
          title_ = other.title_;
          launchDialogType_ = other.launchDialogType_;
          thumbnailUrl_ = other.thumbnailUrl_;
          thumbnailWidth_ = other.thumbnailWidth_;
          thumbnailHeight_ = other.thumbnailHeight_;
          launchUrl_ = other.launchUrl_;
          addedUserId_ = other.addedUserId_;
          reportUrl_ = other.reportUrl_;
          running_ = other.running_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Item Clone() {
          return new Item(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private string id_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Id {
          get { return id_; }
          set {
            id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "entityId" field.</summary>
        public const int EntityIdFieldNumber = 2;
        private string entityId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string EntityId {
          get { return entityId_; }
          set {
            entityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "serviceName" field.</summary>
        public const int ServiceNameFieldNumber = 3;
        private string serviceName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ServiceName {
          get { return serviceName_; }
          set {
            serviceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "title" field.</summary>
        public const int TitleFieldNumber = 4;
        private string title_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Title {
          get { return title_; }
          set {
            title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "launchDialogType" field.</summary>
        public const int LaunchDialogTypeFieldNumber = 5;
        private global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Types.LaunchDialogType launchDialogType_ = global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Types.LaunchDialogType.Small;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Types.LaunchDialogType LaunchDialogType {
          get { return launchDialogType_; }
          set {
            launchDialogType_ = value;
          }
        }

        /// <summary>Field number for the "thumbnailUrl" field.</summary>
        public const int ThumbnailUrlFieldNumber = 6;
        private string thumbnailUrl_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ThumbnailUrl {
          get { return thumbnailUrl_; }
          set {
            thumbnailUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "thumbnailWidth" field.</summary>
        public const int ThumbnailWidthFieldNumber = 7;
        private int thumbnailWidth_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ThumbnailWidth {
          get { return thumbnailWidth_; }
          set {
            thumbnailWidth_ = value;
          }
        }

        /// <summary>Field number for the "thumbnailHeight" field.</summary>
        public const int ThumbnailHeightFieldNumber = 8;
        private int thumbnailHeight_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ThumbnailHeight {
          get { return thumbnailHeight_; }
          set {
            thumbnailHeight_ = value;
          }
        }

        /// <summary>Field number for the "launchUrl" field.</summary>
        public const int LaunchUrlFieldNumber = 9;
        private string launchUrl_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string LaunchUrl {
          get { return launchUrl_; }
          set {
            launchUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "addedUserId" field.</summary>
        public const int AddedUserIdFieldNumber = 10;
        private readonly static string AddedUserIdDefaultValue = "";

        private string addedUserId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string AddedUserId {
          get { return addedUserId_ ?? AddedUserIdDefaultValue; }
          set {
            addedUserId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "addedUserId" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasAddedUserId {
          get { return addedUserId_ != null; }
        }
        /// <summary>Clears the value of the "addedUserId" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearAddedUserId() {
          addedUserId_ = null;
        }

        /// <summary>Field number for the "reportUrl" field.</summary>
        public const int ReportUrlFieldNumber = 11;
        private readonly static string ReportUrlDefaultValue = "";

        private string reportUrl_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ReportUrl {
          get { return reportUrl_ ?? ReportUrlDefaultValue; }
          set {
            reportUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "reportUrl" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasReportUrl {
          get { return reportUrl_ != null; }
        }
        /// <summary>Clears the value of the "reportUrl" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearReportUrl() {
          reportUrl_ = null;
        }

        /// <summary>Field number for the "running" field.</summary>
        public const int RunningFieldNumber = 12;
        private bool running_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Running {
          get { return running_; }
          set {
            running_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Item);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Item other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Id != other.Id) return false;
          if (EntityId != other.EntityId) return false;
          if (ServiceName != other.ServiceName) return false;
          if (Title != other.Title) return false;
          if (LaunchDialogType != other.LaunchDialogType) return false;
          if (ThumbnailUrl != other.ThumbnailUrl) return false;
          if (ThumbnailWidth != other.ThumbnailWidth) return false;
          if (ThumbnailHeight != other.ThumbnailHeight) return false;
          if (LaunchUrl != other.LaunchUrl) return false;
          if (AddedUserId != other.AddedUserId) return false;
          if (ReportUrl != other.ReportUrl) return false;
          if (Running != other.Running) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Id.Length != 0) hash ^= Id.GetHashCode();
          if (EntityId.Length != 0) hash ^= EntityId.GetHashCode();
          if (ServiceName.Length != 0) hash ^= ServiceName.GetHashCode();
          if (Title.Length != 0) hash ^= Title.GetHashCode();
          if (LaunchDialogType != global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Types.LaunchDialogType.Small) hash ^= LaunchDialogType.GetHashCode();
          if (ThumbnailUrl.Length != 0) hash ^= ThumbnailUrl.GetHashCode();
          if (ThumbnailWidth != 0) hash ^= ThumbnailWidth.GetHashCode();
          if (ThumbnailHeight != 0) hash ^= ThumbnailHeight.GetHashCode();
          if (LaunchUrl.Length != 0) hash ^= LaunchUrl.GetHashCode();
          if (HasAddedUserId) hash ^= AddedUserId.GetHashCode();
          if (HasReportUrl) hash ^= ReportUrl.GetHashCode();
          if (Running != false) hash ^= Running.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Id.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Id);
          }
          if (EntityId.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(EntityId);
          }
          if (ServiceName.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(ServiceName);
          }
          if (Title.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Title);
          }
          if (LaunchDialogType != global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Types.LaunchDialogType.Small) {
            output.WriteRawTag(40);
            output.WriteEnum((int) LaunchDialogType);
          }
          if (ThumbnailUrl.Length != 0) {
            output.WriteRawTag(50);
            output.WriteString(ThumbnailUrl);
          }
          if (ThumbnailWidth != 0) {
            output.WriteRawTag(56);
            output.WriteInt32(ThumbnailWidth);
          }
          if (ThumbnailHeight != 0) {
            output.WriteRawTag(64);
            output.WriteInt32(ThumbnailHeight);
          }
          if (LaunchUrl.Length != 0) {
            output.WriteRawTag(74);
            output.WriteString(LaunchUrl);
          }
          if (HasAddedUserId) {
            output.WriteRawTag(82);
            output.WriteString(AddedUserId);
          }
          if (HasReportUrl) {
            output.WriteRawTag(90);
            output.WriteString(ReportUrl);
          }
          if (Running != false) {
            output.WriteRawTag(96);
            output.WriteBool(Running);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Id.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Id);
          }
          if (EntityId.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(EntityId);
          }
          if (ServiceName.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(ServiceName);
          }
          if (Title.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Title);
          }
          if (LaunchDialogType != global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Types.LaunchDialogType.Small) {
            output.WriteRawTag(40);
            output.WriteEnum((int) LaunchDialogType);
          }
          if (ThumbnailUrl.Length != 0) {
            output.WriteRawTag(50);
            output.WriteString(ThumbnailUrl);
          }
          if (ThumbnailWidth != 0) {
            output.WriteRawTag(56);
            output.WriteInt32(ThumbnailWidth);
          }
          if (ThumbnailHeight != 0) {
            output.WriteRawTag(64);
            output.WriteInt32(ThumbnailHeight);
          }
          if (LaunchUrl.Length != 0) {
            output.WriteRawTag(74);
            output.WriteString(LaunchUrl);
          }
          if (HasAddedUserId) {
            output.WriteRawTag(82);
            output.WriteString(AddedUserId);
          }
          if (HasReportUrl) {
            output.WriteRawTag(90);
            output.WriteString(ReportUrl);
          }
          if (Running != false) {
            output.WriteRawTag(96);
            output.WriteBool(Running);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Id.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
          }
          if (EntityId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityId);
          }
          if (ServiceName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ServiceName);
          }
          if (Title.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
          }
          if (LaunchDialogType != global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Types.LaunchDialogType.Small) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LaunchDialogType);
          }
          if (ThumbnailUrl.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ThumbnailUrl);
          }
          if (ThumbnailWidth != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ThumbnailWidth);
          }
          if (ThumbnailHeight != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ThumbnailHeight);
          }
          if (LaunchUrl.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(LaunchUrl);
          }
          if (HasAddedUserId) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(AddedUserId);
          }
          if (HasReportUrl) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ReportUrl);
          }
          if (Running != false) {
            size += 1 + 1;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Item other) {
          if (other == null) {
            return;
          }
          if (other.Id.Length != 0) {
            Id = other.Id;
          }
          if (other.EntityId.Length != 0) {
            EntityId = other.EntityId;
          }
          if (other.ServiceName.Length != 0) {
            ServiceName = other.ServiceName;
          }
          if (other.Title.Length != 0) {
            Title = other.Title;
          }
          if (other.LaunchDialogType != global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Types.LaunchDialogType.Small) {
            LaunchDialogType = other.LaunchDialogType;
          }
          if (other.ThumbnailUrl.Length != 0) {
            ThumbnailUrl = other.ThumbnailUrl;
          }
          if (other.ThumbnailWidth != 0) {
            ThumbnailWidth = other.ThumbnailWidth;
          }
          if (other.ThumbnailHeight != 0) {
            ThumbnailHeight = other.ThumbnailHeight;
          }
          if (other.LaunchUrl.Length != 0) {
            LaunchUrl = other.LaunchUrl;
          }
          if (other.HasAddedUserId) {
            AddedUserId = other.AddedUserId;
          }
          if (other.HasReportUrl) {
            ReportUrl = other.ReportUrl;
          }
          if (other.Running != false) {
            Running = other.Running;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Id = input.ReadString();
                break;
              }
              case 18: {
                EntityId = input.ReadString();
                break;
              }
              case 26: {
                ServiceName = input.ReadString();
                break;
              }
              case 34: {
                Title = input.ReadString();
                break;
              }
              case 40: {
                LaunchDialogType = (global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Types.LaunchDialogType) input.ReadEnum();
                break;
              }
              case 50: {
                ThumbnailUrl = input.ReadString();
                break;
              }
              case 56: {
                ThumbnailWidth = input.ReadInt32();
                break;
              }
              case 64: {
                ThumbnailHeight = input.ReadInt32();
                break;
              }
              case 74: {
                LaunchUrl = input.ReadString();
                break;
              }
              case 82: {
                AddedUserId = input.ReadString();
                break;
              }
              case 90: {
                ReportUrl = input.ReadString();
                break;
              }
              case 96: {
                Running = input.ReadBool();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Id = input.ReadString();
                break;
              }
              case 18: {
                EntityId = input.ReadString();
                break;
              }
              case 26: {
                ServiceName = input.ReadString();
                break;
              }
              case 34: {
                Title = input.ReadString();
                break;
              }
              case 40: {
                LaunchDialogType = (global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet.Types.Item.Types.LaunchDialogType) input.ReadEnum();
                break;
              }
              case 50: {
                ThumbnailUrl = input.ReadString();
                break;
              }
              case 56: {
                ThumbnailWidth = input.ReadInt32();
                break;
              }
              case 64: {
                ThumbnailHeight = input.ReadInt32();
                break;
              }
              case 74: {
                LaunchUrl = input.ReadString();
                break;
              }
              case 82: {
                AddedUserId = input.ReadString();
                break;
              }
              case 90: {
                ReportUrl = input.ReadString();
                break;
              }
              case 96: {
                Running = input.ReadBool();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the Item message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          public enum LaunchDialogType {
            [pbr::OriginalName("SMALL")] Small = 0,
            [pbr::OriginalName("RICHIVIEW")] Richiview = 1,
          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
