// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dwango/nicolive/chat/data/state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dwango.Nicolive.Chat.Data {

  /// <summary>Holder for reflection information generated from dwango/nicolive/chat/data/state.proto</summary>
  public static partial class StateReflection {

    #region Descriptor
    /// <summary>File descriptor for dwango/nicolive/chat/data/state.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL3N0YXRlLnByb3RvEhlkd2Fu",
            "Z28ubmljb2xpdmUuY2hhdC5kYXRhGiVkd2FuZ28vbmljb2xpdmUvY2hhdC9k",
            "YXRhL2F0b21zLnByb3RvGi9kd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL2F0",
            "b21zL21vZGVyYXRvci5wcm90bxotZHdhbmdvL25pY29saXZlL2NoYXQvZGF0",
            "YS9hdG9tcy9ha2FzaGljLnByb3RvGjRkd2FuZ28vbmljb2xpdmUvY2hhdC9k",
            "YXRhL2F0b21zL2ljaGliYWxhdW5jaGVyLnByb3RvGjFkd2FuZ28vbmljb2xp",
            "dmUvY2hhdC9kYXRhL2F0b21zL3N0cmVhbXN0YXRlLnByb3RvIsIICg1OaWNv",
            "bGl2ZVN0YXRlEj4KCnN0YXRpc3RpY3MYASABKAsyJS5kd2FuZ28ubmljb2xp",
            "dmUuY2hhdC5kYXRhLlN0YXRpc3RpY3NIAIgBARI4CgdlbnF1ZXRlGAIgASgL",
            "MiIuZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5FbnF1ZXRlSAGIAQESPQoK",
            "bW92ZV9vcmRlchgDIAEoCzIkLmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEu",
            "TW92ZU9yZGVySAKIAQESOAoHbWFycXVlZRgEIAEoCzIiLmR3YW5nby5uaWNv",
            "bGl2ZS5jaGF0LmRhdGEuTWFycXVlZUgDiAEBEkEKDGNvbW1lbnRfbG9jaxgF",
            "IAEoCzImLmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuQ29tbWVudExvY2tI",
            "BIgBARJBCgxjb21tZW50X21vZGUYBiABKAsyJi5kd2FuZ28ubmljb2xpdmUu",
            "Y2hhdC5kYXRhLkNvbW1lbnRNb2RlSAWIAQESPwoLdHJpYWxfcGFuZWwYByAB",
            "KAsyJS5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLlRyaWFsUGFuZWxIBogB",
            "ARJFCg5wcm9ncmFtX3N0YXR1cxgJIAEoCzIoLmR3YW5nby5uaWNvbGl2ZS5j",
            "aGF0LmRhdGEuUHJvZ3JhbVN0YXR1c0gHiAEBEl0KF21vZGVyYXRpb25fYW5u",
            "b3VuY2VtZW50GAogASgLMjcuZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5h",
            "dG9tcy5Nb2RlcmF0aW9uQW5ub3VuY2VtZW50SAiIAQESVAoPaWNoaWJhX2xh",
            "dW5jaGVyGAsgASgLMjYuZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5hdG9t",
            "cy5JY2hpYmFMYXVuY2hlckl0ZW1TZXRICYgBARJUChNzdHJlYW1fc3RhdGVf",
            "Y2hhbmdlGAwgASgLMjIuZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5hdG9t",
            "cy5TdHJlYW1TdGF0ZUNoYW5nZUgKiAEBElAKDWFrYXNoaWNfc3RhdGUYDSAB",
            "KAsyNC5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zLkFrYXNoaWNT",
            "dGF0ZVJvdXRpbmdIC4gBAUINCgtfc3RhdGlzdGljc0IKCghfZW5xdWV0ZUIN",
            "CgtfbW92ZV9vcmRlckIKCghfbWFycXVlZUIPCg1fY29tbWVudF9sb2NrQg8K",
            "DV9jb21tZW50X21vZGVCDgoMX3RyaWFsX3BhbmVsQhEKD19wcm9ncmFtX3N0",
            "YXR1c0IaChhfbW9kZXJhdGlvbl9hbm5vdW5jZW1lbnRCEgoQX2ljaGliYV9s",
            "YXVuY2hlckIWChRfc3RyZWFtX3N0YXRlX2NoYW5nZUIQCg5fYWthc2hpY19z",
            "dGF0ZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dwango.Nicolive.Chat.Data.AtomsReflection.Descriptor, global::Dwango.Nicolive.Chat.Data.Atoms.ModeratorReflection.Descriptor, global::Dwango.Nicolive.Chat.Data.Atoms.AkashicReflection.Descriptor, global::Dwango.Nicolive.Chat.Data.Atoms.IchibalauncherReflection.Descriptor, global::Dwango.Nicolive.Chat.Data.Atoms.StreamstateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.NicoliveState), global::Dwango.Nicolive.Chat.Data.NicoliveState.Parser, new[]{ "Statistics", "Enquete", "MoveOrder", "Marquee", "CommentLock", "CommentMode", "TrialPanel", "ProgramStatus", "ModerationAnnouncement", "IchibaLauncher", "StreamStateChange", "AkashicState" }, new[]{ "Statistics", "Enquete", "MoveOrder", "Marquee", "CommentLock", "CommentMode", "TrialPanel", "ProgramStatus", "ModerationAnnouncement", "IchibaLauncher", "StreamStateChange", "AkashicState" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NicoliveState : pb::IMessage<NicoliveState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NicoliveState> _parser = new pb::MessageParser<NicoliveState>(() => new NicoliveState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NicoliveState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dwango.Nicolive.Chat.Data.StateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NicoliveState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NicoliveState(NicoliveState other) : this() {
      statistics_ = other.statistics_ != null ? other.statistics_.Clone() : null;
      enquete_ = other.enquete_ != null ? other.enquete_.Clone() : null;
      moveOrder_ = other.moveOrder_ != null ? other.moveOrder_.Clone() : null;
      marquee_ = other.marquee_ != null ? other.marquee_.Clone() : null;
      commentLock_ = other.commentLock_ != null ? other.commentLock_.Clone() : null;
      commentMode_ = other.commentMode_ != null ? other.commentMode_.Clone() : null;
      trialPanel_ = other.trialPanel_ != null ? other.trialPanel_.Clone() : null;
      programStatus_ = other.programStatus_ != null ? other.programStatus_.Clone() : null;
      moderationAnnouncement_ = other.moderationAnnouncement_ != null ? other.moderationAnnouncement_.Clone() : null;
      ichibaLauncher_ = other.ichibaLauncher_ != null ? other.ichibaLauncher_.Clone() : null;
      streamStateChange_ = other.streamStateChange_ != null ? other.streamStateChange_.Clone() : null;
      akashicState_ = other.akashicState_ != null ? other.akashicState_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NicoliveState Clone() {
      return new NicoliveState(this);
    }

    /// <summary>Field number for the "statistics" field.</summary>
    public const int StatisticsFieldNumber = 1;
    private global::Dwango.Nicolive.Chat.Data.Statistics statistics_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.Statistics Statistics {
      get { return statistics_; }
      set {
        statistics_ = value;
      }
    }

    /// <summary>Field number for the "enquete" field.</summary>
    public const int EnqueteFieldNumber = 2;
    private global::Dwango.Nicolive.Chat.Data.Enquete enquete_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.Enquete Enquete {
      get { return enquete_; }
      set {
        enquete_ = value;
      }
    }

    /// <summary>Field number for the "move_order" field.</summary>
    public const int MoveOrderFieldNumber = 3;
    private global::Dwango.Nicolive.Chat.Data.MoveOrder moveOrder_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.MoveOrder MoveOrder {
      get { return moveOrder_; }
      set {
        moveOrder_ = value;
      }
    }

    /// <summary>Field number for the "marquee" field.</summary>
    public const int MarqueeFieldNumber = 4;
    private global::Dwango.Nicolive.Chat.Data.Marquee marquee_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.Marquee Marquee {
      get { return marquee_; }
      set {
        marquee_ = value;
      }
    }

    /// <summary>Field number for the "comment_lock" field.</summary>
    public const int CommentLockFieldNumber = 5;
    private global::Dwango.Nicolive.Chat.Data.CommentLock commentLock_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.CommentLock CommentLock {
      get { return commentLock_; }
      set {
        commentLock_ = value;
      }
    }

    /// <summary>Field number for the "comment_mode" field.</summary>
    public const int CommentModeFieldNumber = 6;
    private global::Dwango.Nicolive.Chat.Data.CommentMode commentMode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.CommentMode CommentMode {
      get { return commentMode_; }
      set {
        commentMode_ = value;
      }
    }

    /// <summary>Field number for the "trial_panel" field.</summary>
    public const int TrialPanelFieldNumber = 7;
    private global::Dwango.Nicolive.Chat.Data.TrialPanel trialPanel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.TrialPanel TrialPanel {
      get { return trialPanel_; }
      set {
        trialPanel_ = value;
      }
    }

    /// <summary>Field number for the "program_status" field.</summary>
    public const int ProgramStatusFieldNumber = 9;
    private global::Dwango.Nicolive.Chat.Data.ProgramStatus programStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.ProgramStatus ProgramStatus {
      get { return programStatus_; }
      set {
        programStatus_ = value;
      }
    }

    /// <summary>Field number for the "moderation_announcement" field.</summary>
    public const int ModerationAnnouncementFieldNumber = 10;
    private global::Dwango.Nicolive.Chat.Data.Atoms.ModerationAnnouncement moderationAnnouncement_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.Atoms.ModerationAnnouncement ModerationAnnouncement {
      get { return moderationAnnouncement_; }
      set {
        moderationAnnouncement_ = value;
      }
    }

    /// <summary>Field number for the "ichiba_launcher" field.</summary>
    public const int IchibaLauncherFieldNumber = 11;
    private global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet ichibaLauncher_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet IchibaLauncher {
      get { return ichibaLauncher_; }
      set {
        ichibaLauncher_ = value;
      }
    }

    /// <summary>Field number for the "stream_state_change" field.</summary>
    public const int StreamStateChangeFieldNumber = 12;
    private global::Dwango.Nicolive.Chat.Data.Atoms.StreamStateChange streamStateChange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.Atoms.StreamStateChange StreamStateChange {
      get { return streamStateChange_; }
      set {
        streamStateChange_ = value;
      }
    }

    /// <summary>Field number for the "akashic_state" field.</summary>
    public const int AkashicStateFieldNumber = 13;
    private global::Dwango.Nicolive.Chat.Data.Atoms.AkashicStateRouting akashicState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dwango.Nicolive.Chat.Data.Atoms.AkashicStateRouting AkashicState {
      get { return akashicState_; }
      set {
        akashicState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NicoliveState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NicoliveState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Statistics, other.Statistics)) return false;
      if (!object.Equals(Enquete, other.Enquete)) return false;
      if (!object.Equals(MoveOrder, other.MoveOrder)) return false;
      if (!object.Equals(Marquee, other.Marquee)) return false;
      if (!object.Equals(CommentLock, other.CommentLock)) return false;
      if (!object.Equals(CommentMode, other.CommentMode)) return false;
      if (!object.Equals(TrialPanel, other.TrialPanel)) return false;
      if (!object.Equals(ProgramStatus, other.ProgramStatus)) return false;
      if (!object.Equals(ModerationAnnouncement, other.ModerationAnnouncement)) return false;
      if (!object.Equals(IchibaLauncher, other.IchibaLauncher)) return false;
      if (!object.Equals(StreamStateChange, other.StreamStateChange)) return false;
      if (!object.Equals(AkashicState, other.AkashicState)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (statistics_ != null) hash ^= Statistics.GetHashCode();
      if (enquete_ != null) hash ^= Enquete.GetHashCode();
      if (moveOrder_ != null) hash ^= MoveOrder.GetHashCode();
      if (marquee_ != null) hash ^= Marquee.GetHashCode();
      if (commentLock_ != null) hash ^= CommentLock.GetHashCode();
      if (commentMode_ != null) hash ^= CommentMode.GetHashCode();
      if (trialPanel_ != null) hash ^= TrialPanel.GetHashCode();
      if (programStatus_ != null) hash ^= ProgramStatus.GetHashCode();
      if (moderationAnnouncement_ != null) hash ^= ModerationAnnouncement.GetHashCode();
      if (ichibaLauncher_ != null) hash ^= IchibaLauncher.GetHashCode();
      if (streamStateChange_ != null) hash ^= StreamStateChange.GetHashCode();
      if (akashicState_ != null) hash ^= AkashicState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (statistics_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Statistics);
      }
      if (enquete_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Enquete);
      }
      if (moveOrder_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MoveOrder);
      }
      if (marquee_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Marquee);
      }
      if (commentLock_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CommentLock);
      }
      if (commentMode_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(CommentMode);
      }
      if (trialPanel_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TrialPanel);
      }
      if (programStatus_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(ProgramStatus);
      }
      if (moderationAnnouncement_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(ModerationAnnouncement);
      }
      if (ichibaLauncher_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(IchibaLauncher);
      }
      if (streamStateChange_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(StreamStateChange);
      }
      if (akashicState_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(AkashicState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (statistics_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Statistics);
      }
      if (enquete_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Enquete);
      }
      if (moveOrder_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MoveOrder);
      }
      if (marquee_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Marquee);
      }
      if (commentLock_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CommentLock);
      }
      if (commentMode_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(CommentMode);
      }
      if (trialPanel_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TrialPanel);
      }
      if (programStatus_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(ProgramStatus);
      }
      if (moderationAnnouncement_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(ModerationAnnouncement);
      }
      if (ichibaLauncher_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(IchibaLauncher);
      }
      if (streamStateChange_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(StreamStateChange);
      }
      if (akashicState_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(AkashicState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (statistics_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Statistics);
      }
      if (enquete_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Enquete);
      }
      if (moveOrder_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MoveOrder);
      }
      if (marquee_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Marquee);
      }
      if (commentLock_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CommentLock);
      }
      if (commentMode_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CommentMode);
      }
      if (trialPanel_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrialPanel);
      }
      if (programStatus_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ProgramStatus);
      }
      if (moderationAnnouncement_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ModerationAnnouncement);
      }
      if (ichibaLauncher_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IchibaLauncher);
      }
      if (streamStateChange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StreamStateChange);
      }
      if (akashicState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AkashicState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NicoliveState other) {
      if (other == null) {
        return;
      }
      if (other.statistics_ != null) {
        if (statistics_ == null) {
          Statistics = new global::Dwango.Nicolive.Chat.Data.Statistics();
        }
        Statistics.MergeFrom(other.Statistics);
      }
      if (other.enquete_ != null) {
        if (enquete_ == null) {
          Enquete = new global::Dwango.Nicolive.Chat.Data.Enquete();
        }
        Enquete.MergeFrom(other.Enquete);
      }
      if (other.moveOrder_ != null) {
        if (moveOrder_ == null) {
          MoveOrder = new global::Dwango.Nicolive.Chat.Data.MoveOrder();
        }
        MoveOrder.MergeFrom(other.MoveOrder);
      }
      if (other.marquee_ != null) {
        if (marquee_ == null) {
          Marquee = new global::Dwango.Nicolive.Chat.Data.Marquee();
        }
        Marquee.MergeFrom(other.Marquee);
      }
      if (other.commentLock_ != null) {
        if (commentLock_ == null) {
          CommentLock = new global::Dwango.Nicolive.Chat.Data.CommentLock();
        }
        CommentLock.MergeFrom(other.CommentLock);
      }
      if (other.commentMode_ != null) {
        if (commentMode_ == null) {
          CommentMode = new global::Dwango.Nicolive.Chat.Data.CommentMode();
        }
        CommentMode.MergeFrom(other.CommentMode);
      }
      if (other.trialPanel_ != null) {
        if (trialPanel_ == null) {
          TrialPanel = new global::Dwango.Nicolive.Chat.Data.TrialPanel();
        }
        TrialPanel.MergeFrom(other.TrialPanel);
      }
      if (other.programStatus_ != null) {
        if (programStatus_ == null) {
          ProgramStatus = new global::Dwango.Nicolive.Chat.Data.ProgramStatus();
        }
        ProgramStatus.MergeFrom(other.ProgramStatus);
      }
      if (other.moderationAnnouncement_ != null) {
        if (moderationAnnouncement_ == null) {
          ModerationAnnouncement = new global::Dwango.Nicolive.Chat.Data.Atoms.ModerationAnnouncement();
        }
        ModerationAnnouncement.MergeFrom(other.ModerationAnnouncement);
      }
      if (other.ichibaLauncher_ != null) {
        if (ichibaLauncher_ == null) {
          IchibaLauncher = new global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet();
        }
        IchibaLauncher.MergeFrom(other.IchibaLauncher);
      }
      if (other.streamStateChange_ != null) {
        if (streamStateChange_ == null) {
          StreamStateChange = new global::Dwango.Nicolive.Chat.Data.Atoms.StreamStateChange();
        }
        StreamStateChange.MergeFrom(other.StreamStateChange);
      }
      if (other.akashicState_ != null) {
        if (akashicState_ == null) {
          AkashicState = new global::Dwango.Nicolive.Chat.Data.Atoms.AkashicStateRouting();
        }
        AkashicState.MergeFrom(other.AkashicState);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (statistics_ == null) {
              Statistics = new global::Dwango.Nicolive.Chat.Data.Statistics();
            }
            input.ReadMessage(Statistics);
            break;
          }
          case 18: {
            if (enquete_ == null) {
              Enquete = new global::Dwango.Nicolive.Chat.Data.Enquete();
            }
            input.ReadMessage(Enquete);
            break;
          }
          case 26: {
            if (moveOrder_ == null) {
              MoveOrder = new global::Dwango.Nicolive.Chat.Data.MoveOrder();
            }
            input.ReadMessage(MoveOrder);
            break;
          }
          case 34: {
            if (marquee_ == null) {
              Marquee = new global::Dwango.Nicolive.Chat.Data.Marquee();
            }
            input.ReadMessage(Marquee);
            break;
          }
          case 42: {
            if (commentLock_ == null) {
              CommentLock = new global::Dwango.Nicolive.Chat.Data.CommentLock();
            }
            input.ReadMessage(CommentLock);
            break;
          }
          case 50: {
            if (commentMode_ == null) {
              CommentMode = new global::Dwango.Nicolive.Chat.Data.CommentMode();
            }
            input.ReadMessage(CommentMode);
            break;
          }
          case 58: {
            if (trialPanel_ == null) {
              TrialPanel = new global::Dwango.Nicolive.Chat.Data.TrialPanel();
            }
            input.ReadMessage(TrialPanel);
            break;
          }
          case 74: {
            if (programStatus_ == null) {
              ProgramStatus = new global::Dwango.Nicolive.Chat.Data.ProgramStatus();
            }
            input.ReadMessage(ProgramStatus);
            break;
          }
          case 82: {
            if (moderationAnnouncement_ == null) {
              ModerationAnnouncement = new global::Dwango.Nicolive.Chat.Data.Atoms.ModerationAnnouncement();
            }
            input.ReadMessage(ModerationAnnouncement);
            break;
          }
          case 90: {
            if (ichibaLauncher_ == null) {
              IchibaLauncher = new global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet();
            }
            input.ReadMessage(IchibaLauncher);
            break;
          }
          case 98: {
            if (streamStateChange_ == null) {
              StreamStateChange = new global::Dwango.Nicolive.Chat.Data.Atoms.StreamStateChange();
            }
            input.ReadMessage(StreamStateChange);
            break;
          }
          case 106: {
            if (akashicState_ == null) {
              AkashicState = new global::Dwango.Nicolive.Chat.Data.Atoms.AkashicStateRouting();
            }
            input.ReadMessage(AkashicState);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (statistics_ == null) {
              Statistics = new global::Dwango.Nicolive.Chat.Data.Statistics();
            }
            input.ReadMessage(Statistics);
            break;
          }
          case 18: {
            if (enquete_ == null) {
              Enquete = new global::Dwango.Nicolive.Chat.Data.Enquete();
            }
            input.ReadMessage(Enquete);
            break;
          }
          case 26: {
            if (moveOrder_ == null) {
              MoveOrder = new global::Dwango.Nicolive.Chat.Data.MoveOrder();
            }
            input.ReadMessage(MoveOrder);
            break;
          }
          case 34: {
            if (marquee_ == null) {
              Marquee = new global::Dwango.Nicolive.Chat.Data.Marquee();
            }
            input.ReadMessage(Marquee);
            break;
          }
          case 42: {
            if (commentLock_ == null) {
              CommentLock = new global::Dwango.Nicolive.Chat.Data.CommentLock();
            }
            input.ReadMessage(CommentLock);
            break;
          }
          case 50: {
            if (commentMode_ == null) {
              CommentMode = new global::Dwango.Nicolive.Chat.Data.CommentMode();
            }
            input.ReadMessage(CommentMode);
            break;
          }
          case 58: {
            if (trialPanel_ == null) {
              TrialPanel = new global::Dwango.Nicolive.Chat.Data.TrialPanel();
            }
            input.ReadMessage(TrialPanel);
            break;
          }
          case 74: {
            if (programStatus_ == null) {
              ProgramStatus = new global::Dwango.Nicolive.Chat.Data.ProgramStatus();
            }
            input.ReadMessage(ProgramStatus);
            break;
          }
          case 82: {
            if (moderationAnnouncement_ == null) {
              ModerationAnnouncement = new global::Dwango.Nicolive.Chat.Data.Atoms.ModerationAnnouncement();
            }
            input.ReadMessage(ModerationAnnouncement);
            break;
          }
          case 90: {
            if (ichibaLauncher_ == null) {
              IchibaLauncher = new global::Dwango.Nicolive.Chat.Data.Atoms.IchibaLauncherItemSet();
            }
            input.ReadMessage(IchibaLauncher);
            break;
          }
          case 98: {
            if (streamStateChange_ == null) {
              StreamStateChange = new global::Dwango.Nicolive.Chat.Data.Atoms.StreamStateChange();
            }
            input.ReadMessage(StreamStateChange);
            break;
          }
          case 106: {
            if (akashicState_ == null) {
              AkashicState = new global::Dwango.Nicolive.Chat.Data.Atoms.AkashicStateRouting();
            }
            input.ReadMessage(AkashicState);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
